import './globals.css'
import type { Metadata } from 'next'
import { Inter, Alef } from 'next/font/google'
import Image from 'next/image'
import Link from 'next/link'

const inter = Alef({ weight: "700", subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Marcos Gutiérrez',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}, min-h-screen bg-gradient-to-b from-black to-sky-700`}>
        <nav className='text-white bg-black flex items-center justify-between p-3'>
          <Link href={"/"} className='flex items-center gap-2'>
            <Image src='https://media.licdn.com/dms/image/D4D03AQEUI108__rKgA/profile-displayphoto-shrink_400_400/0/1674665524926?e=1700697600&v=beta&t=ZEb1namajjsHuok7r7VBPuHwcYjxGlo6IUFQM2aH4hE' className='rounded-[50%] h-[6rem] w-[6rem]' height={40} width={90} alt={"foto"}/>
            <h1 className='text-2xl'>Marcos Gutiérrez Moya</h1>
          </Link>
          <section className='flex items-center gap-12'>
            <Link href={"/web"} className='text-[2rem]'>Web</Link>
            <Link href={"https://react-arena.vercel.app/"} target='_blank' className='text-[2rem]'>9<sup>3/4</sup></Link>
            <Link href={"/videogames"} className='text-[2rem]'>Videojuegos</Link>
          </section>
          <section className='flex items-center gap-4 pl-36'>
            <Link href={"https://github.com/MarcosGutierrezMoya?tab=repositories"} target="_blank" className='flex items-center gap-2'>
              <img src="https://static-00.iconduck.com/assets.00/github-icon-2048x1988-jzvzcf2t.png" alt="github icon" className='h-8'/>
              <p className='text-[1.25rem]'>Github</p>
              </Link>
            <Link href={"https://www.linkedin.com/in/marcos-gutierrez-moya/"} target="_blank" className='flex items-center gap-2'>
              <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/LinkedIn_icon_circle.svg/800px-LinkedIn_icon_circle.svg.png" alt="github icon" className='h-8'/>
              <p className='text-[1.25rem]'>Linkedin</p>
              </Link>
          </section>
        </nav>
        {children}
      </body>
    </html>
  )
}
