import './globals.css'
import type { Metadata } from 'next'
import { Aldrich } from 'next/font/google'
import AnswerContextProvider from './_componentes/context'

const inter = Aldrich({ weight: "400", subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Marcos Gutiérrez',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen bg-gradient-to-b from-black to-sky-950`}>
      <AnswerContextProvider>
        {children}
      </AnswerContextProvider>
      </body>
    </html>
  )
}
