import type { Metadata } from 'next'
import { Inter, Alef } from 'next/font/google'

const inter = Alef({ weight: "700", subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Web',
  description: 'Generated by create next app',
}

export default function VideogamesLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <section className={inter.className}>
        {children}
      </section>
    </html>
  )
}
