import type { Metadata } from 'next'
import { Aldrich } from 'next/font/google'
import { AuthProvider } from '../context/AuthContext';

const inter = Aldrich({ weight: "400", subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Web',
  description: 'Generated by create next app',
}

export default function VideogamesLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <section className={`${inter.className}`}>
      <AuthProvider>
        {children}
      </AuthProvider>
    </section>
  )
}
